# Code generated by `./update.sh master` DO NOT EDIT.
# generated at Sun Mar 10 17:33:16 GMT 2019
{ lib, fetchGitHubFiles }:

let
  repo = {
    owner = "ryanoasis";
    repo = "nerd-fonts";
    rev = "d43a49c14cd053e348835e7ad0595f9a85579bca";
  };
  fontSrc = { name, sha256, override ? null}:
    let
      patch = if override == null then font: font
                else font: font // (override font);
    in
    {
      inherit name;
      src = fetchGitHubFiles (patch {
        name = "nerdfonts-${lib.toLower name}-${repo.rev}-src";
        inherit (repo) owner repo rev;
        paths = [ "src/unpatched-fonts/${name}" ];
        inherit sha256;
      });
    };
in
{
  version = "2.0.0-dev";
  font-patcher = fetchGitHubFiles {
    name = "nerdfonts-patcher-${repo.rev}-src";
    inherit (repo) owner repo rev;
    paths = [
      "font-patcher"
      "src/glyphs"
    ];
    sha256 = "0fqsnl96fp0n6b7gmwqmp23709hshd7hck38pr3j78y8c38l63gm";
  };

  fonts = map (fontSrc) [
    {name = "3270"; sha256 = "1j4j8w9m8smxzixd632xiih525ridwyjig26cq72bgd36qc8fbrl";}
    {name = "AnonymousPro"; sha256 = "14vw4bdrb8md9yaa7y8mx79y52gphg8vb0a2j0yjkagjqf7q4hmd";}
    {name = "Arimo"; sha256 = "0lj0h0hjjjrn1aqfppxzn5ap5si1qgcivs0vn0jv9drvvc0cwipm";}
    {name = "AurulentSansMono"; sha256 = "1yh8c0wf59anxf4arhdx7crjj65ksjq9ank2ypghk0p4hmqcf1d4";}
    {name = "BigBlueTerminal"; sha256 = "0rkb1q1wlziggar3dfk5mlncdssyw92vi21pcp1g16s0gchkwgph";}
    {name = "BitstreamVeraSansMono"; sha256 = "0ciahn0mq7hw0fznanvlprcaf3f4qgrz1lvbdcl9prr54x1a0941";}
    {name = "Blex"; sha256 = "1bpgdijs9igm3ihjcdwh8ilhx8icr5l5knw331ggnvz3wv2irmh4";}
    {name = "CodeNewRoman"; sha256 = "11sjz8pb6fa0y2sa2qc2yqzzf6ry3vx0jm5zkjm76gpscvz62pya";}
    {name = "Cousine"; sha256 = "12xy4m9h9nin1acpn8ymaqwrz2i53ry8hnhmp1xx0i6zqdw3q1in";}
    {name = "DejaVuSansMono"; sha256 = "0kcfkdiwfhclxarg267pf6i1xarf31qiz7vhvbqky8fl66n38rn2";}
    {name = "DroidSansMono"; sha256 = "1dn0pz1vkq79pwh8fxg7pqyginiascbx66z6airz6f0vfx6yj8r3";}
    {name = "FantasqueSansMono"; sha256 = "1wm58csjz067dgb245y6svamkg1rdlywa5w6iv5ndmayskm60nw3";}
    {name = "FiraCode"; sha256 = "1pm72rksyg56dpg04lf64brskqdlwa14sbq1lsiarm2665fny6dk";}
    {name = "FiraMono"; sha256 = "0his6q84zi009nnmyvcpdjbzr3x19asn7f42nmvrpdsnyi1a69r2";}
    {name = "Gohu"; sha256 = "1gp0hk7bwdjin7ax43nb2bq8q2irq0n8ic6r3gjwnh890a225zzh";}
    {name = "Go-Mono"; sha256 = "02d6gdw1k2m1m9pg4p4vp7vjyl9844a31lq5rj7jfyxmx9xqkkil";}
    {name = "Hack"; sha256 = "0zi59wz9lzjjaq8iw2242rig1fc3yd5bzb8q25lvnajr2xbrahr7"; override = (old: {
        paths = old.paths ++ [ "bin/scripts/Hack" ];
      });
    }
    {name = "Hasklig"; sha256 = "1s1awvsgfi0pfcryhxcmj679r87n1r2j7jdsb1pwirq16hybls38";}
    {name = "HeavyData"; sha256 = "1f99dda4mgiw9mfri01pa6ss7cxagw90c48s4ivsvylljff7nyxd";}
    {name = "Hermit"; sha256 = "165ix4c93rx8f6dm1d6hjx55by3ryglj9z98d28g7dcp01fk4vwx";}
    {name = "Inconsolata"; sha256 = "1mx845vg1nxbyd3bsvlpidcvpzsvmjm90nawmz7bi6xnqi9cr5fh";}
    {name = "InconsolataGo"; sha256 = "00rlcq9x04yq0272fyx23dxd0gppp03cxmi1dmznfwjx3wr3zjm7";}
    {name = "InconsolataLGC"; sha256 = "10vghlr522n6h6gg06nsv67irml4mcl4v07cshbz26qjda30ywwa";}
    {name = "Iosevka"; sha256 = "0mzgd26rrjyicx5fpdvq2h5a3bshnyk3nzbrgm5vccjnqc9lfszz";}
    {name = "Lekton"; sha256 = "1z69rn6qv1yi86cpfzyhjamgyzy776hcv6rbqdg1r9avvbz6d6m3";}
    {name = "LiberationMono"; sha256 = "1m823hiwv8z7wa20xjfp9h8c36ablpncbkp0rmdr5wafapxq4pwp";}
    {name = "Meslo"; sha256 = "0a9xdmw78q7sssmzm7bqgcdiljzjy3z7swq23p4rax5d40iqqg2g";}
    {name = "Monofur"; sha256 = "1bgm46gvxhynd4lqqg53qawq7j1zrjlv1vv7845zsvhndyh712c6";}
    {name = "Monoid"; sha256 = "0rfipp2ggfk7sjvd696ykdfwy320qadx5gqyr28qaczaa7fh9bd4";}
    {name = "Mononoki"; sha256 = "1v9g7hi38qam3dd9xw4695r5n6ni7viw3586a202zz1ffbj82nyk";}
    {name = "MPlus"; sha256 = "05py45dg075cnhzcdhsjp2xiyi2r2hwvxxqh46i6r1lkz8zr0vwz";}
    {name = "Noto"; sha256 = "1fbvmcdxhwgl9nqcjknj8a4451q3p4xk2fqmifgda96w4ghhiy4s";}
    {name = "OpenDyslexic"; sha256 = "0hzka2crc9szw6h21nhl48kcsyyhnri0ynkwly56qbnn3hf09pkv";}
    {name = "Overpass"; sha256 = "0dcbda7lq8wf9hh0vs38m6jc905mmbxc51mz7xxix9cxdn9nq6dq";}
    {name = "ProFont"; sha256 = "1dr6znpvlq9aaiv2xlg334rriap7i5nbx5xdwspsyjn5r6njsr4c";}
    {name = "ProggyClean"; sha256 = "0abcxwl7chr2r58z7s48mbkc1vkaxc9a0kdm5zrfnmhpshw8b4s4";}
    {name = "RobotoMono"; sha256 = "15ycj5j8cpkr8jdgaagnv1g717sfhfdbmlzhzgywfdhgi2jljkyd";}
    {name = "ShareTechMono"; sha256 = "13vwdck4140m2qway7vwrvdb5274cmbqpyqs6ffzlahm109lfmdm";}
    {name = "SourceCodePro"; sha256 = "1mba367fkx2j4fqhg9a2wjzjwhpimighbz1smy38hr2n6vh2icp3";}
    {name = "SpaceMono"; sha256 = "0v2s4ihwd2p6gma513f40xc43ppf5dbdqls6dh0ikz0jbbhn0jic";}
    {name = "Terminus"; sha256 = "1spss2sx1k5w8bhrq5nsmmcd98f8dqxgrb3hhbscgys7df4c7qkd";}
    {name = "Tinos"; sha256 = "1x43bnlyyshb5d60iqbdzax4y3hmjkn1k115v5aj353xsp8sfjaz";}
    {name = "Ubuntu"; sha256 = "1snvwijkhsbjvsgfx59rq45wqvyjcqwrq3q7f1bd26q4xss1y9vz";}
    {name = "UbuntuMono"; sha256 = "1f08zcm55psgpk929ygfyg10d3xq33ws8brr3fqhc8n072w48zx7";}
  ];
}
